### PR TITLE
Minimum viable change for compile on Solaris 11.

### PR DESCRIPTION
**Pull request by PCOWandre**

### CODE REVIEW

**Comment by GregTheMadMonk** [comment]
Thanks for the contribution!
I will merge it, but before I have some questions (sorry if they are stupid):
1. In Makefile, you create two variables `UNAME_S` and `UNAME_R`, their values are the same, and only `UNAME_S` is used. Is there a motivation for `UNAME_R` to exist?
2. If the solution is for Solaris 11, wouldn't it be better to add `-fpermissive` only when building on it?
If this is how things are intended to be, I have no problem with that. If not, you can change it, or, if you don't want to, I will merge it as it is and make changes myself.

*Also, there's no need in **curses.h** in **noaftodo_config.cpp**, but that's my mistake)*

**Comment by PCOWandre** [comment]
I'll fix the Makefile, I spotted another error in there anyway. I was originally going to trap for early Solaris releases but figured nobody is likely building on pre-11 these days.

The permissive looks like it might pop up at some point in the future on other platforms:

```
src/noaftodo_daemon.cpp:44:13: warning: ISO C++ forbids comparison between pointer and integer [-fpermissive]
src/noaftodo_daemon.cpp:198:13: warning: ISO C++ forbids comparison between pointer and integer [-fpermissive]
```

I'm so not a c++ guy, so I'll leave the details in your court for this one.

**Comment by GregTheMadMonk** [comment]
I'm not much of a "C++ guy" too) Anyway, I have no problem with it being the way you made it.
Accepted, and thanks!

**Comment by PCOWandre** [comment]
Cheers! Best of luck with your project.

**Pull request merged**
